### ISSUE TITLE
Noise Plethora Grit control is reversed and filter do not self oscillate

### ISSUE THREAD

**Issue by omricohenmusic** [VCVRack/Befaco#34]
Hi!

Thanks again for bringing this beautiful module to VCV! I have also the hardware and I noticed that the grit quantity knob is reversed so there are fewer grains to the right in VCV, while in hardware it's when turning it to the left. 
Another thing I noticed is that in hardware, the filters will self oscillate at one point, but in VCV, they do not. 

I'm not so sure if this is on purpose or not, but I thought I will let you know. 
I'm sure you have enough to deal with now in your personal life (congrats once again!) so take your time with this. 

Cheers!
Omri

**Comment by hemmer** [comment]
Hey, thanks for the report (no baby yet!). Re grit, you are totally right. I have an earlier prototype in my rack where Grit works the other direction, but Manu did mention that the release version would be different. Not sure whether to fix (and break a few people's initial patches) or to leave as is? 

Re filters - yeah I am aware of this and made a choice to use a relatively simple SVF which indeed doesn't self oscillate in order to prioritise getting all the noise algorithms in. You can still get sort-of close (e.g. kicks and things out of it) at full resonance (e.g. given a little bit of grit), but self-oscillation would be nice. Maybe an enhancement for a future update?

**Comment by hemmer** [comment]
Pushed an update to the library for grit knob, hopefully it'll be in soon!

**Comment by omricohenmusic** [comment]
Hi,

I just saw that you made the change to the grit knob. Thanks for that. About the filters, I guess that since it's a hardware clone, people will want to test it before they buy it so maybe it's better to add this feature. To be honest, I like it more in VCV because I can just crank up the resonance without worrying about getting a tone, but it can also be useful having more oscillations, adding character and such.
I guess that if it's technically possible, it's better to add this feature.

Thanks again!
________________________________

**Comment by hemmer** [comment]
Yeah fair point. I will add a note to https://github.com/VCVRack/Befaco#differences-with-hardware and put it on the backlog for something to consider in future. It isn't trivial to add self-resonance with the current filter model though, so probably it won't be for a while. Thanks for the feedback!
