### ISSUE TITLE
Rampage unstable at shape = -1

### ISSUE THREAD

**Issue by hemmer** [VCVRack/Befaco#44]
![image](https://github.com/VCVRack/Befaco/assets/915048/aa5d6ca0-7539-48e4-b613-a85d1dec5a46)

When shape is left-most, we get noise in the outs. The issue wasn't present when the module was monophonic, and so maybe due to the SIMD porting. It appears to be connected to improper termination of the cycle, as there's a lot of activity on the rising/falling outputs.

**Comment by DaveBenham** [comment]
That trailing noise is wonderful for creating a snare - simply ping a Wasp filter.

Since this is emulating actual hardware, I am sure you want to get rid of that noise. But maybe consider providing a context menu option to add the noise. I've got a patch that depends on the noise, so I am interested in keeping that behavior. But I have to admit, if I was responsible for the module I would probably banish the noise forever.

**Comment by hemmer** [comment]
It's actually pretty serious and affects the operation in lots of ways (e.g. when feeding something into IN which I don't often do). I've pushed a fix @DaveBenham, can you confirm it's "working" for you? https://github.com/hemmer/Befaco/releases

As for leaving it in as an option, sadly I think for maintainability / not confusing the user, I'll just fix this / banish forever. Befaco collection already suffers from a lot of context menu overload already, and this is just too far towards bug on the "bug <-> feature" spectrum for me. Sorry about that - you can easily revert my changes in a local copy (or patch it up similarily 🙈 ).

Thanks for the report!

**Comment by DaveBenham** [comment]
Looks to have solved the problem! Working great on my Windows machine.

No worries about banishing the bug. I'm sure that is what I would have done. Plus I already have a modified patch that resurrects the snare via an extra Rampage, some noise, and a VCA Mixer
